// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


// import 'firebase_options.dart';
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVt2DkUuEj5ysd6ONOJqfJ86PKW0Hl59g',
    appId: '1:554547915603:web:ace9731fa31ff83ec78fa6',
    messagingSenderId: '554547915603',
    projectId: 'henkeldasksh-adminpanel',
    authDomain: 'henkeldasksh-adminpanel.firebaseapp.com',
    storageBucket: 'henkeldasksh-adminpanel.appspot.com',
    measurementId: 'G-0JVEVQJ5L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP-EeTO5c0SB7wBQiDWyoPUnhBxcF5lCA',
    appId: '1:554547915603:android:9914fa0a94f16ecfc78fa6',
    messagingSenderId: '554547915603',
    projectId: 'henkeldasksh-adminpanel',
    storageBucket: 'henkeldasksh-adminpanel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKTmU9YlLmIGSLdqLzNiBrhFKrcYLClo',
    appId: '1:554547915603:ios:0649c969b7cc9c61c78fa6',
    messagingSenderId: '554547915603',
    projectId: 'henkeldasksh-adminpanel',
    storageBucket: 'henkeldasksh-adminpanel.appspot.com',
    iosClientId: '554547915603-u0lvtegfgf90eslagfd5unvsqcakid8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.henkelDakshProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPKTmU9YlLmIGSLdqLzNiBrhFKrcYLClo',
    appId: '1:554547915603:ios:3b288985588b4b01c78fa6',
    messagingSenderId: '554547915603',
    projectId: 'henkeldasksh-adminpanel',
    storageBucket: 'henkeldasksh-adminpanel.appspot.com',
    iosClientId: '554547915603-tbajkjq6r45qcaaj90uikkbp2474paek.apps.googleusercontent.com',
    iosBundleId: 'com.example.henkelDakshProject.RunnerTests',
  );
}
